# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtx" do
  name "wtx"
  desc "Git worktree management CLI"
  homepage "https://github.com/t-shiratori/wtx"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtx"

  on_macos do
    on_intel do
      url "https://github.com/t-shiratori/wtx/releases/download/v#{version}/wtx_darwin_amd64.tar.gz",
        verified: "github.com/t-shiratori/wtx"
      sha256 "44d30aacfdc7e725047ee3485179bd8c8a950ce075ce1b7a3ec1de38e529373b"
    end
    on_arm do
      url "https://github.com/t-shiratori/wtx/releases/download/v#{version}/wtx_darwin_arm64.tar.gz",
        verified: "github.com/t-shiratori/wtx"
      sha256 "05d3c2aedbf3e99968349d055d0810476ad89bc3810af40ece2d736f556ef13f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtx"]
    end
  end

  # No zap stanza required
end
