# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtx" do
  name "wtx"
  desc "Git worktree management CLI"
  homepage "https://github.com/t-shiratori/wtx"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtx"

  on_macos do
    on_intel do
      url "https://github.com/t-shiratori/wtx/releases/download/v#{version}/wtx_darwin_amd64.tar.gz",
        verified: "github.com/t-shiratori/wtx"
      sha256 "f7d5df1e66a808213d1b9148c4a122c723d4fdf29da23d81f3adbd2c39b3927c"
    end
    on_arm do
      url "https://github.com/t-shiratori/wtx/releases/download/v#{version}/wtx_darwin_arm64.tar.gz",
        verified: "github.com/t-shiratori/wtx"
      sha256 "2825fa87761be4e971202d16fa5de3ddf03faa762173582c9ed571361b55734f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtx"]
    end
  end

  # No zap stanza required
end
