# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtx" do
  name "wtx"
  desc "Git worktree management CLI"
  homepage "https://github.com/t-shiratori/wtx"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtx"

  on_macos do
    on_intel do
      url "https://github.com/t-shiratori/wtx/releases/download/v#{version}/wtx_darwin_amd64.tar.gz",
        verified: "github.com/t-shiratori/wtx"
      sha256 "561de33f3289e7221f41ad75aafa47adb91c420d1ab74c4c048d8bdac38c5a4b"
    end
    on_arm do
      url "https://github.com/t-shiratori/wtx/releases/download/v#{version}/wtx_darwin_arm64.tar.gz",
        verified: "github.com/t-shiratori/wtx"
      sha256 "0f90a54b463936f08bd8e4377764eb538be2fa32ed06822484da3ee2bccc8ade"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtx"]
    end
  end

  # No zap stanza required
end
